import "@radix-ui/themes/styles.css";
import "./globals.css";

import { Box, Flex, Theme } from "@radix-ui/themes";

import type { Metadata } from "next";
import NavBar from "@/ui/layout/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-mono`}>
        <Theme appearance="light">
          <Flex width="100%" direction="column">
            <NavBar />
            <Box py="5"></Box>
            {children}
          </Flex>
        </Theme>
      </body>
    </html>
  );
}
