import "@radix-ui/themes/styles.css";
import "./globals.css";

import { Box, Flex, Theme } from "@radix-ui/themes";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import NavBar from "@/ui/layout/navbar";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-mono`}>
        <ThemeProvider attribute="class">
          <Theme>
            <Flex width="100%" direction="column">
              <NavBar />
              <Box py="5"></Box>
              {children}
            </Flex>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
